<?php

namespace UserBundle\Repository;

/**
 * SalarieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalarieRepository extends \Doctrine\ORM\EntityRepository
{
}
