<?php

namespace Proxies\__CG__\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Salarie extends \UserBundle\Entity\Salarie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'user', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'id', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'nom', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'prenom', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'img', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'dateNaissance', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'sexe', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'dateEntre', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'typeContrat', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'dureeContrat', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'salaire', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'superieurHierarchique'];
        }

        return ['__isInitialized__', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'user', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'id', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'nom', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'prenom', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'img', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'dateNaissance', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'sexe', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'dateEntre', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'typeContrat', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'dureeContrat', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'salaire', '' . "\0" . 'UserBundle\\Entity\\Salarie' . "\0" . 'superieurHierarchique'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Salarie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance($dateNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEntre($dateEntre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEntre', [$dateEntre]);

        return parent::setDateEntre($dateEntre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEntre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEntre', []);

        return parent::getDateEntre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeContrat($typeContrat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeContrat', [$typeContrat]);

        return parent::setTypeContrat($typeContrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeContrat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeContrat', []);

        return parent::getTypeContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeContrat($dureeContrat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeContrat', [$dureeContrat]);

        return parent::setDureeContrat($dureeContrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeContrat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeContrat', []);

        return parent::getDureeContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalaire($salaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalaire', [$salaire]);

        return parent::setSalaire($salaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalaire', []);

        return parent::getSalaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperieurHierarchique($superieurHierarchique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperieurHierarchique', [$superieurHierarchique]);

        return parent::setSuperieurHierarchique($superieurHierarchique);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuperieurHierarchique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuperieurHierarchique', []);

        return parent::getSuperieurHierarchique();
    }

    /**
     * {@inheritDoc}
     */
    public function getImg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImg', []);

        return parent::getImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setImg($img)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImg', [$img]);

        return parent::setImg($img);
    }

}
