<?php

namespace ForumBundle\Repository;

/**
 * RepliesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepliesRepository extends \Doctrine\ORM\EntityRepository
{
}
